const FUNCTION = 0;
const USERS_COLLECTION = "users";
const COUNTRIES_COLLECTION = "countries";
const DECLARE_MATCHES_COLLECTION = "declare_matches";
const MATCHMAKING_COLLECTION = "matchmaking";
const MATCHMAKING_HISTORY_COLLECTION = "history";
const PLATFORMS_COLLECTION = "platforms";
const PLAYERS_COLLECTION = "players";
const ROLES_COLLECTION = "roles";
const PREFIX_REGISTER_PLAYER = "regPlayer";
const REGISTER_TAG_POSITION = 1;
const REGISTER_NAME_POSITION = 2;
const REGISTER_COUNTRY_CODE_POSITION = 3;
const REGISTER_PLATFORM_POSITION = 4;
const REGISTER_HOURS_POSITION = 5;
const PREFIX_REGISTER = "register";
const REGISTER_ROLE_POSITION = 2;
const PREFIX_REGISTER_COUNTRY = "regCountry";
const COUNTRY_NAME = 1;
const COUNTRY_CODE = 2;
const PREFIX_REGISTER_PLATFORM = "regPlatform";
const PLATFORM_NAME = 1;
const PLATFORM_CODE = 2;
const PREFIX_MATCHMAKE = "matchmake";
const PREFIX_MATCH_END = "end-match";
const PREFIX_MATCH_DECLARE = "challenge";
const PREFIX_ACCEPT_MATCH = "accept";
const PREFIX_LIST = "list";
const PREFIX_PROFILE = "profile";
const PREFIX_RATING = "rating";

module.exports.PREFIX = {
    FUNCTION: FUNCTION,
    USERS_COLLECTION: USERS_COLLECTION,
    COUNTRIES_COLLECTION: COUNTRIES_COLLECTION,
    DECLARE_MATCHES_COLLECTION: DECLARE_MATCHES_COLLECTION,
    MATCHMAKING_COLLECTION: MATCHMAKING_COLLECTION,
    MATCHMAKING_HISTORY_COLLECTION: MATCHMAKING_HISTORY_COLLECTION,
    PLATFORMS_COLLECTION: PLATFORMS_COLLECTION,
    PLAYERS_COLLECTION: PLAYERS_COLLECTION,
    ROLES_COLLECTION: ROLES_COLLECTION,
    PREFIX_REGISTER_PLAYER: PREFIX_REGISTER_PLAYER,
    REGISTER_TAG_POSITION: REGISTER_TAG_POSITION,
    REGISTER_NAME_POSITION: REGISTER_NAME_POSITION,
    REGISTER_COUNTRY_CODE_POSITION: REGISTER_COUNTRY_CODE_POSITION,
    REGISTER_PLATFORM_POSITION: REGISTER_PLATFORM_POSITION,
    REGISTER_HOURS_POSITION: REGISTER_HOURS_POSITION,
    PREFIX_REGISTER: PREFIX_REGISTER,
    REGISTER_ROLE_POSITION: REGISTER_ROLE_POSITION,
    PREFIX_REGISTER_COUNTRY: PREFIX_REGISTER_COUNTRY,
    COUNTRY_NAME: COUNTRY_NAME,
    COUNTRY_CODE: COUNTRY_CODE,
    PREFIX_REGISTER_PLATFORM: PREFIX_REGISTER_PLATFORM,
    PLATFORM_NAME: PLATFORM_NAME,
    PLATFORM_CODE: PLATFORM_CODE,
    PREFIX_MATCHMAKE: PREFIX_MATCHMAKE,
    PREFIX_MATCH_END: PREFIX_MATCH_END,
    PREFIX_MATCH_DECLARE: PREFIX_MATCH_DECLARE,
    PREFIX_ACCEPT_MATCH: PREFIX_ACCEPT_MATCH,
    PREFIX_LIST: PREFIX_LIST,
    PREFIX_PROFILE: PREFIX_PROFILE,
    PREFIX_RATING: PREFIX_RATING,
}